enable-rpc=true
rpc-listen-all=false
rpc-listen-port=6800
rpc-allow-origin-all=true
dir=/downloads
file-allocation=none
bt-max-peers=300
seed-time=0
continue=true
max-concurrent-downloads=5
enable-dht=true
bt-enable-lpd=true
listen-port=6882
dht-listen-port=6882
dht-entry-point=dht.transmissionbt.com:6881
dht-file-path=/data/dht.dat
input-file=/data/aria2.session
save-session=/data/aria2.session
save-session-interval=15
console-log-level=notice
allow-overwrite=true
auto-file-renaming=true
bt-remove-unselected-file=true
bt-tracker=udp://tracker.opentrackr.org:1337/announce,udp://exodus.desync.com:6969/announce,udp://tracker.torrent.eu.org:451/announce,udp://open.stealth.si:80/announce,udp://tracker.moeking.me:6969/announce,udp://tracker.cyberia.is:6969/announce,udp://ipv4.tracker.harry.lu:80/announce,http://sukebei.tracker.wf:8888/announce
