from __future__ import annotations

import re

# Scene releases use namer `{site}`: spaces gone, then Site.YY.MM.DD.
# This catalog turns a TPDB studio name (and its aliases) into those prefixes.

_APOSTROPHE = re.compile(r"[’']")
_PARENS = re.compile(r"\([^)]*\)|\[[^\]]*\]")
_WORD = re.compile(r"[A-Za-z0-9]+")
_GENERIC_TAIL = {
    "porn", "porno", "xxx", "media", "films", "film", "productions",
    "entertainment", "network", "official", "studio", "studios", "com",
    "compilations", "compilation", "collection", "collections", "anthology",
}
_GENERIC_SITE_TAIL = {"porn", "xxx", "vr", "official", "originals", "com"}
# VR-first studios whose names do not contain vr / virtual / slr.
# xbvr's official SLR list plus common TPDB names. Names with those
# markers are detected in is_vr_studio without being listed here.
_VR_COMPACT = {
    "sexlikereal", "lustreality", "hornyhostel", "erotiquesex",
    "eroticsinners", "realitylovers", "swallowbay", "dezyred",
    "virtualtaboo", "astrodomina", "blondehexe", "blusherotica",
    "bravomodelsmedia", "casanova", "covertjapan", "deepinsex",
    "emilybloom", "heathering", "jimmydraws", "kinkygirlsberlin",
    "peepingthom", "petersmax", "sweetlonglips", "tadpolexxxstudio",
    "thatrandomeditor", "povr", "baberoticavr", "amateurcouplesvr",
    "hologirlsvr", "stasyqvr",
}
_VR_TAG_NAMES = {
    "virtual reality", "vr glasses", "180°", "180", "360°", "360", "oculus",
}
# Tags that show up as the site head in P2P names, not generated by removing spaces.
_KNOWN_PREFIXES = {
    "brazzersexxtra": ["BEX"],
    "brazzers": ["BZR"],
    "propertysex": ["PSE"],
    "sexlikereal": ["SLR"],
    "slroriginals": ["SLR"],
    "naughtyamericavr": ["NAVR"],
    "vrcosplayx": ["VRCX"],
    "vrbangers": ["VRB"],
    "vrhush": ["VRH"],
    "virtualrealporn": ["VRP"],
    "wankzvr": ["WVR"],
    "badoinkvr": ["BVR"],
    "sexbabesvr": ["SBVR"],
    "18vr": ["18VR"],
    "realjamvr": ["RJVR"],
    "povr": ["POVR"],
    "vrconk": ["VRC"],
    "darkroomvr": ["DRVR"],
    "fuckpassvr": ["FPVR"],
    "tmwvrnet": ["TMW"],
    "czechvr": ["CVR"],
    "passionhd": ["PHD"],
    "tiny4k": ["T4K"],
    "ddfnetwork": ["DDF"],
    "fakehub": ["FHUB"],
    "faketaxi": ["FKTX"],
    "letsdoeit": ["LDI"],
    "agirlknows": ["AGK"],
    "nfbusty": ["NFB"],
    "hookuphotshot": ["HUHS"],
    "adulttime": ["ADT"],
    "puretaboo": ["PTBO"],
    "sweetsinner": ["SWSN"],
    "newsensations": ["NSS"],
    "teamskeet": ["TSKT"],
    "nubilefilms": ["NBF"],
    "legalporno": ["LGPO"],
    "21sextury": ["21S"],
}


def compact_site(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", (text or "").lower())


def studio_tokens(site: str) -> list[str]:
    """Keep VR, NF, 18, 4K, and the A in A Girl Knows. Titles do not use this."""
    cleaned = _PARENS.sub(" ", _APOSTROPHE.sub("", site or ""))
    raw: list[str] = []
    for word in _WORD.findall(cleaned):
        if word.isdigit():
            if len(word) >= 2:
                raw.append(word)
            continue
        if len(word) >= 2 or word.isalpha():
            raw.append(word)
    if not any(len(tok) >= 2 for tok in raw):
        return []
    return raw[:5]


def _add_form(forms: list[str], item: str) -> None:
    item = (item or "").strip(" .")
    if not item:
        return
    if any(existing.lower() == item.lower() for existing in forms):
        return
    forms.append(item)


def _vr_swapped(tokens: list[str]) -> str | None:
    if len(tokens) < 2:
        return None
    lower = [tok.lower() for tok in tokens]
    if lower[0] == "vr":
        swapped = "".join(tokens[1:] + tokens[:1])
    elif lower[-1] == "vr":
        swapped = "".join(tokens[-1:] + tokens[:-1])
    else:
        return None
    if len(compact_site(swapped)) < 5:
        return None
    return swapped


def _core_tokens(tokens: list[str]) -> list[str]:
    """Peel catalog filler from either end of a studio name."""
    body = list(tokens)
    if len(body) >= 2 and body[0].lower() == "the":
        body = body[1:]
    if len(body) >= 3 and body[1].lower() == "of" and len(body[0]) <= 4:
        body = body[2:]
    while len(body) >= 2 and body[-1].lower() in _GENERIC_TAIL:
        body = body[:-1]
    return body


def _forms_for_name(name: str) -> list[str]:
    tokens = studio_tokens(name)
    if not tokens:
        compact = compact_site(name)
        return [compact] if compact else []
    compact = "".join(tokens)
    forms: list[str] = []
    _add_form(forms, compact)
    _add_form(forms, ".".join(tokens))
    swapped = _vr_swapped(tokens)
    if swapped:
        _add_form(forms, swapped)
    if tokens[0].lower() == "the" and len(tokens) >= 2:
        _add_form(forms, "".join(tokens[1:]))
    if tokens[-1].lower() in _GENERIC_TAIL and len(tokens) >= 2:
        trimmed = "".join(tokens[:-1])
        if len(compact_site(trimmed)) >= 5:
            _add_form(forms, trimmed)
    initials = "".join(word if len(word) <= 2 else word[0] for word in tokens)
    if len(initials) >= 3:
        _add_form(forms, initials)
    if len(tokens) >= 2 and 3 <= len(tokens[0]) <= 4 and tokens[0].isupper():
        _add_form(forms, tokens[0])
    for alias in _KNOWN_PREFIXES.get(compact_site(compact), []):
        _add_form(forms, alias)
    core = _core_tokens(tokens)
    if core != tokens and len(compact_site("".join(core))) >= 5:
        for form in _forms_for_name(" ".join(core)):
            _add_form(forms, form)
    return forms


def release_prefixes(site: str, extra_names: list[str] | None = None) -> list[str]:
    """P2P / namer prefixes for one studio, plus TPDB aliases when given."""
    forms: list[str] = []
    names = [site, *(extra_names or [])]
    for name in names:
        for form in _forms_for_name(name):
            _add_form(forms, form)
    return forms[:8]


def site_names(row: dict) -> list[str]:
    """Display name, slug, and aliases from a ThePornDB site record."""
    names: list[str] = []

    def add(text: object) -> None:
        item = str(text or "").strip()
        if item and item not in names:
            names.append(item)

    add(row.get("name"))
    slug = str(row.get("slug") or "").strip().replace("-", " ")
    add(slug)
    aliases = row.get("aliases") or row.get("alias") or []
    if isinstance(aliases, str):
        aliases = [aliases]
    for alias in aliases:
        if isinstance(alias, dict):
            add(alias.get("name") or alias.get("slug"))
        else:
            add(alias)
    return names


def pick_site(rows: list, query: str) -> dict | None:
    """Resolve a search box or filename studio onto one TPDB site."""
    wanted = compact_site(query)
    if len(wanted) < 4:
        return None
    query_fold = (query or "").strip().casefold()
    exact: list[dict] = []
    compact_exact: list[dict] = []
    generic: list[dict] = []
    for row in rows:
        if not isinstance(row, dict) or not row.get("id"):
            continue
        labels = site_names(row)
        if not labels:
            continue
        for name in labels:
            compact = compact_site(name)
            if not compact:
                continue
            if name.casefold() == query_fold:
                exact.append(row)
                break
            if compact == wanted:
                compact_exact.append(row)
                break
            if (
                len(wanted) >= 5
                and compact.startswith(wanted)
                and compact[len(wanted):] in _GENERIC_SITE_TAIL
            ):
                generic.append(row)
                break
    for group in (exact, compact_exact, generic):
        if len(group) == 1:
            return group[0]
        if len(group) > 1:
            group.sort(key=lambda row: len(str(row.get("name") or "")))
            return group[0]
    return None


def is_vr_studio(site: str) -> bool:
    tokens = [tok.lower() for tok in studio_tokens(site)]
    compact = compact_site(site)
    if "vr" in tokens or "vr" in compact:
        return True
    if "virtual" in compact:
        return True
    if compact.startswith("slr") or compact in _VR_COMPACT:
        return True
    return False


def is_slr_studio(site: str) -> bool:
    """SLR dumps look like SLR_SexBabesVR_NancyA_Title, not Site.YY.MM.DD."""
    return is_vr_studio(site)


def uses_slr_names(site: str, extra_names: list[str] | None = None, vr: bool = False) -> bool:
    if vr or is_vr_studio(site):
        return True
    return any(is_vr_studio(name) for name in extra_names or [])


def is_vr_work(site: str = "", tags: list | None = None, title: str = "") -> bool:
    if is_vr_studio(site):
        return True
    for tag in tags or []:
        name = str(tag or "").casefold().strip()
        if name in _VR_TAG_NAMES or name.startswith("vr "):
            return True
    blob = f"{site} {title}"
    return bool(re.search(r"(?i)(?<![a-z0-9])vr(?![a-z0-9])", blob))
